; config.ini

[macmachine]  ; 默认节 (可选)
data_dir = /Users/qiushi/Desktop/traindata
[winmachine]  ; 默认节 (可选)
data_dir = F:\\标记数据\\traindata
[ubuntumachine]
data_dir=/root/traindata
[common] ; 其他节 (可选)
img_dir = img
model_dir = models
window_stride = 2560
useSwanLab = False
log_dir=./training_logs
[dir1] ; 其他节 (可选)
img_dir = img1
model_dir = models1
window_stride = 2560
useSwanLab = False
[dir2] ; 其他节 (可选)
img_dir = img2
model_dir = models2
window_stride = 2560
useSwanLab = False
[dir3] ; 其他节 (可选)
img_dir = img3
model_dir = models3
window_stride = 2560
useSwanLab = False
[dirgan]
img_dir = imggan
model_dir = modelgan
window_stride = 2560
useSwanLab = False
[dirgan1]
img_dir = imggan1
model_dir = modelgan1
window_stride = 2560
useSwanLab = False
[dirgan2]
img_dir = imggan2
model_dir = modelgan2
window_stride = 2560
useSwanLab = False
[dirganlog]
img_dir = imgganlog
model_dir = modelganlog
window_stride = 2560
[dirbase]
img_dir = imgdirbase
model_dir = modeldirbase
window_stride = 2560
useSwanLab = False
[dirbase1]
img_dir = imgdirbase1
model_dir = modeldirbase1
window_stride = 2560
useSwanLab = False
[dirbase2]
img_dir = imgdirbase2
model_dir = modeldirbase2
window_stride = 2560
useSwanLab = False
[dirganbase1]
img_dir = imgdirganbase1
model_dir = modeldirganbase1
window_stride = 2560
useSwanLab = False
[dirganbase2]
img_dir = imgdirganbase2
model_dir = modeldirganbase2
window_stride = 2560
useSwanLab = False
[dirganbase3]
img_dir = imgdirganbase3
model_dir = modeldirganbase3
window_stride = 2560
useSwanLab = False


